#!groovy
// Run docker build
pipeline {
    agent {
        label 'master'
     }

    stages {
        stage("create docker image") {
            steps {
                echo " ============== start building image =================="
                dir ('docker/toolbox') {
                	sh 'docker build -t "jenkins_selenium" . '
                }
            }
        }
        stage("run docker container") {
            steps {
                echo " ============== run docker container =================="
                	sh 'docker run --rm jenkins_selenium'
            }
        }
        stage('Reports') {
            steps {
                allure([
                    includeProperties: false,
                    jdk: '',
                    properties: [],
                    reportBuildPolicy: 'ALWAYS',
                    results: [[path: 'target/allure-results']]
                ])
            }
        }
    }
}