#!groovy
// Run docker build
pipeline {
    agent {
        label 'master'
     }

    stages {
        stage("create docker image") {
            steps {
                echo " ============== start building image =================="
                dir ('docker/toolbox') {
                	sh 'sudo docker build -t "jenkins_selenium" . '
                }
            }
        }
        stage("run docker container") {
            steps {
                echo " ============== run docker container =================="
                	sh 'sudo docker run -it --rm jenkins_selenium sh'
            }
        }
    }
}